# Generated by Django 5.1.2 on 2024-10-24 11:03

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producttag_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='products/'),
        ),
    ]
