# Generated by Django 5.1.2 on 2024-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
