# Generated by Django 5.1.2 on 2024-10-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
