# Generated by Django 5.1.2 on 2024-10-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/thumbnails/'),
        ),
    ]
