# Generated by Django 5.1.2 on 2024-11-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description_en_product_description_ge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_ge',
            new_name='description_ka',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_ge',
            new_name='name_ka',
        ),
    ]
